name: Test Workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "Workflow triggered successfully!"

      # Set up the latest stable version of the Dart SDK.
      - uses: dart-lang/setup-dart@v1

      # Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'  # Specify the exact version here
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test fire_app/test/widget_test.dart